### ISSUE TITLE
rotating is laggy

### ISSUE THREAD

**Issue by Akuli** [Arrinao/tetris#20]
squares aren't redrawn after rotating

**Comment by Arrinao** [comment]
Fixed by commit a34a9d7939cac7e9a09df7ec0d4177c6b91b66e

I still think we should redesign the way block_rotator works, in order to be able to utilize mediators in GUI like user_input _left and right functions do. Currently the new shape of the block is only displayed after it has moved down.

**Comment by Akuli** [comment]
>Currently the new shape of the block is only displayed after it has moved down.

This is exactly what this issue is about. If that still happens, then this is not fixed yet.
